spring:
  application:
    name: api-gateway-zuul

server:
  port: 9003

zuul:
  routes:
    provider1:
      url: http://localhost:9005/
      path: /provider1/**
    secur:
      url: http://localhost:9004/
      path: /secur/**
    auth:
      url: http://localhost:9006/
      path: /auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 1

ribbon:
  eureka:
#    ribbon禁掉Eureka
    enabled: false