server:
  port: 9005

spring:
  application:
    name: api-provider1
  security:
    user:
      name: admin
      password: admin123

eureka:
  client:
    serviceUrl:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9002/eureka/
      defaultZone: http://localhost:9002/eureka/
      #healthcheck:
        #enabled: true #开启自定义健康检查
  instance:
    # eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例(开发环境)
    lease-expiration-duration-in-seconds: 10
    #eureka客户端要向eureka服务器发送心跳的频率，默认30秒(开发环境)
    lease-renewal-interval-in-seconds: 1

ribbon:
  eureka:
    enabled: true